### ISSUE TITLE
Valid example request

### ISSUE THREAD

**Issue by szokodiakos** [ifml/ifml-editor#12]
Hello!

I have been trying out this neat editor for some time now, but I cannot create a diagram which passes the tool's validation (Right click > Validate diagram).

I have tried out the example movie IFML, but the editor says it has 20 errors. I have tried to resolve them manually, but at some point I could not figure out how to advance (not even with the help of the IFML standard PDF from OMG's website).

I have also tried to create a very simple IFML from scratch (two Windows and a ParameterBinding in between them), but when I added the ParameterBinding between the Windows, I could not resolve the validator's error messages.

Could you please provide a fully valid example (or modify the movies example to pass validation)? It would really help me!

Thank you in advance.

Akos

**Comment by hamzaed** [comment]
Hi Akos,

Thanks for you interest in using the open source IFML editor and thanks for pointing out the issue. 

I updated the movie example. Now it's valid but you need to update the plugin because the metamodel has been changed.

Sincerely,
Hamza
