### ISSUE TITLE
Cannot complete the install because one or more required items could not be found.

### ISSUE THREAD

**Issue by magick93** [ifml/ifml-editor#14]
Hi

I'm trying to install the IFML plugin, but am getting the following error:

Cannot complete the install because one or more required items could not be found.
  Software being installed: IFML editor 1.0.0.201412021412 (org.ifml.editor.feature.feature.group 1.0.0.201412021412)
  Missing requirement: Sirius Core Runtime 1.0.0.201406040902 (org.eclipse.sirius 1.0.0.201406040902) requires 'bundle org.eclipse.gmf.runtime.emf.core 1.4.1' but it could not be found
  Cannot satisfy dependency:
    From: IFML editor 1.0.0.201412021412 (org.ifml.editor.feature.feature.group 1.0.0.201412021412)
    To: org.eclipse.sirius 0.0.0

How can i fix this?

Thanks

**Comment by hamzaed** [comment]
Hi,

Make sure that yo're using the modeling distribution of Eclipse Luna. You can find it here : http://www.eclipse.org/downloads/packages/eclipse-modeling-tools/lunasr1

Thanks for your interest in the IFML editor.

Hamza
