### ISSUE TITLE
Generating code

### ISSUE THREAD

**Issue by rbanks721** [ifml/ifml-editor#17]
Now that I have the IFML Editor working I would like to generate code like Java Swing or HTML using it using Acceleo. Where can I find the model templates? Because the Acceleo plugin is not working on Eclipse Luna I have to use the Standalone Java Application Runner but I am not sure how to register the metamodel. I am using the example movie.core model and keep getting the following:

Exception in thread "main" org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: org.eclipse.emf.ecore.xmi.PackageNotFoundException: Package with uri 'http://www.omg.org/spec/20130218/core' not found. (file:/C:/Development/IDE/Eclipse/UMLDesigner/workspace/org.ifml.sample/models/movie.core, 2, 264)

**Comment by hamzaed** [comment]
Hi, 
The Acceleo plugin is working on Eclipse Luna, some parts of the editor are done with acceleo. If you used the update site then the metamodel is already registred. In the case where  you imported the the source code from the repository then  you have to create your Acceleo porject in the second instance of Eclipse.

**Comment by rbanks721** [comment]
I was able to get to generate code running as standalone. Where can I find the model templates for Java Swing, and HTML? How can I save the IFML models I create? Do I need to download and compile the current IFML Editor source code?

**Comment by marcinkunert** [comment]
HI @rbanks721 

have you managed to figure it out? I am struggling with a very similar problem and could use some help. I would love to hear from you here or per email: the.martines@gmail.com

Greetings
Marcin

**Comment by rbanks721** [comment]
Hi Marcin,

Yes, I was able to finally generate the code using Acceleo under Standalone
Java Application Runner setting. What issues are you having?

The main issue I was the modal URI reference settings and use IFMLWindow
instead of Window. Please see code sample below:

[comment encoding = UTF-8 /]

[module main('http://www.omg.org/spec/20130218/core', '
http://www.omg.org/spec/20130218/ext', 'http://www.omg.org/spec/UML', '
http://www.omg.org/spec/IFML', 'http://www.omg.org/spec/IFML/core', '
http://www.omg.org/spec/IFML/ext', 'http://www.eclipse.org/uml2/5.0.0/UML')]

[import org::ifml::ifml2javaswing1::main::form /]
[import org::ifml::ifml2javaswing1::main::details /]
[import org::ifml::ifml2javaswing1::main::index /]
[import org::ifml::ifml2javaswing1::main::action /]

[template public main(ifmlModel : IFMLModel)]

[comment @main/]
[for (element : InteractionFlowModelElement |
ifmlModel.interactionFlowModel.interactionFlowModelElements)]
[   if (element.oclIsTypeOf(IFMLWindow))]
      [file (element.oclAsType(IFMLWindow).name.toUpperFirst().concat(
'.java'), false, 'Cp1252')]

 import javax.swing.*;
import java.awt.GridLayout;
import java.awt.event.ActionEent;
import java.awt.event.ActionListener;

/// ... //

```
  public class [element.oclAsType(IFMLWindow).name.toUpperFirst()/]
```

extends [if(element.oclAsType(IFMLWindow).isModal)]JDialog implements
ActionListener [else] JFrame [/if]  {

```
  }

  [/file]
```

   [/if]
[/for]
[/template]

Regards,
Ricardy
