### ISSUE TITLE
The IFML Diagram does not come up when using provided sample.

### ISSUE THREAD

**Issue by kray42** [ifml/ifml-editor#20]
I installed the tool as instructed in http://ifml.github.io/ in the latest version of eclipse, Eclipse Version: Mars Release (4.5.0).
I could follow the sample upto the last instruction. The only problem is that no diagram shows up.
As you can see from the attached screenshot, the project shows up properly in the Model Explorer, but no diagram is drawn in the 'new IFMLDiagram'.
![screenshot-eclipse](https://cloud.githubusercontent.com/assets/2011408/9296412/182adfc6-44aa-11e5-800d-8f95a4901ba3.jpg)

**Comment by hamzaed** [comment]
Hi Kaustabh,

Thank you for your interest in IFML editor. The steps in the web page describe how to initialize an empty diagram. In the step [Create a Core model](http://ifml.github.io/#core_model), we're creating an empty core file. You have to use the palette at the right side to add elements to the diagram. The last screenshot shows an example that you can get by using the tool. You can check this sample from [Github](https://github.com/ifml/ifml-editor/tree/master/examples/org.ifml.sample) as described in the last step.

Best regards,
Hamza
